application: manipalconvocation15
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /crontask
  script:  main.app
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
- name: ssl
  version: latest
